apiVersion: v1
kind: Pod
metadata: 
 name: pod 
spec: 
  containers: 
    - name: java12
      image: nginx 
      env: 
        - name: course 
          valueFrom: 
            configMapKeyRef: 
             name:  config 
             key: course 